root /var/www/site;
index index.php index.html;

client_max_body_size    256m;
client_body_buffer_size	4m;

types_hash_max_size	4096;

add_header X-Content-Type-Options nosniff always;
add_header X-Frame-Options SAMEORIGIN always;

location / {
    try_files $uri $uri/ /bitrix/urlrewrite.php$is_args$args;
}

# restrict dot-files
location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
}

# bitrix internal locations
location ~* ^/(bitrix|local)/(modules|local_cache|stack_cache|managed_cache|php_interface) {
    deny all;
}

# upload 1c files
location ~* ^/upload/1c_[^/]+/ {
    deny all;
}

location ~* ^/upload/.*\.(php|php3|php4|php5|phtml)$ {
    deny all;
}

# use the file system to access files outside the site (cache)
location ~* /\.\./ { deny all; }
location ~* ^/bitrix/html_pages/\.config\.php { deny all; }
location ~* ^/bitrix/html_pages/\.enabled { deny all; }

location ~ \.php$ {
    try_files $uri =404;

    include fastcgi.conf;
    fastcgi_pass php:9000;
    fastcgi_read_timeout 300;
    fastcgi_send_timeout 300;
}

location ~* \.(jpg|jpeg|png|gif|webp|avif|svg|ico|css|js|map|woff2?|ttf|eot|otf|mp4|webm)$ {
    log_not_found off;
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
}

error_page 500 502 503 504 /500.html;
error_page 404 = /404.php;
