access_log /dev/stdout;
error_log  /dev/stderr warn;

root /var/www/bitrix;
index index.php index.html;

client_max_body_size    256m;
client_body_buffer_size	4m;

# Parameters for back-end request proxy
proxy_connect_timeout      300;
proxy_send_timeout         300;
proxy_read_timeout         300;
proxy_buffer_size          64k;
proxy_buffers              8 256k;
proxy_busy_buffers_size    256k;
proxy_temp_file_write_size 10m;

types_hash_max_size	4096;

add_header "X-Content-Type-Options" "nosniff";
add_header X-Frame-Options SAMEORIGIN;

location / {
    try_files $uri $uri/ /bitrix/urlrewrite.php$is_args$args;
}

# restrict dot-files
location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
}

# bitrix internal locations
location ~* ^/(bitrix|local)/(modules|local_cache|stack_cache|managed_cache|php_interface) {
    deny all;
}

# upload 1c files
location ~* ^/upload/1c_[^/]+/ {
    deny all;
}

# use the file system to access files outside the site (cache)
location ~* /\.\./ { deny all; }
location ~* ^/bitrix/html_pages/\.config\.php { deny all; }
location ~* ^/bitrix/html_pages/\.enabled { deny all; }

location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass php:9000;
    fastcgi_index index.php;
    fastcgi_read_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}

location ~* \.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|eot|otf|ttf|woff|woff2)$ {
    log_not_found off;
    access_log off;
    expires 30d;
    add_header Cache-Control public;
}

error_page 500 502 503 504 /500.html;
error_page 404 = /404.php;
